server:
  mode: debug
  addr: :80
  read_timeout: 10
  write_timeout: 10

app:
  log_path: /home/cheung/site/go/runtime/log
  secret:
  root_path: go_cms
  app_path: app

database:
  type: mysql
  user: root
  password: AnightOflower@7 
  name: go_cms
  charset: utf8mb4
